### PR TITLE
GIP: rename chrome_ext to browser-extension

### PR DESCRIPTION
**Pull request by gasolin**
Rename `gitcoinco/chrome_ext` to `gitcoinco/gitcoin-extension` to reflect the repo's purpose

### CODE REVIEW

**Comment by owocki** [comment]
how about calling it `gitcoinco/browser-extension` ?

**Comment by gasolin** [comment]
`browser-extension` sounds good to me. 

Is there any other concern around the proposal?

**Comment by owocki** [comment]
dont think so.  will let this sit one more day then execute the xfr

**Comment by owocki** [comment]
🎉 https://github.com/gitcoinco/browser-extension

**Pull request merged**
