### PR TITLE
adds GIP-1

### PR DESCRIPTION
**Pull request by owocki**
## Preamble

    GIP: 1
    Title: GIP 1-- GIP Process
    Author: Kevin Owocki (kevin@gitcoin.co), Mark Beacom (mark.beacom@consensys.net)
    Type: Meta
    Status: Draft
    Created: 2018-03-12
    Requires (*optional): None
    Replaces (*optional): None

## Simple Summary
The community has great ideas, and we would like to solicit their input about the way the Gitcoin product is managed.

## Abstract
The community has great ideas, and we would like to solicit their input about the way the Gitcoin product is managed.

The community is already familiar with Ethereum EIPs ( https://github.com/ethereum/EIPs ).  The GIP process (which is a fork of EIPs) is process is meant to use their familiarity with that process in order to make it easier for them to give input to the Gitcoin community.

## Motivation

* Solicit the community's ideas
* Provide an open forum for discussion / debate.

## Specification
(see the gip-1.md doc in the PR)

## Rationale

* It's working for Ethereum
* The gitcoin community has grown large enough that we need something like this.

## Backwards Compatibility
N/A

## Test Cases
N/A

## Implementation
N/A

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

### CODE REVIEW

**Comment by owocki** [comment]
> @e-n-l approved this pull request.

hehe did you just approve our own PR

**Comment by owocki** [comment]
> hehe did you just approve our own PR

i am so dumb.  this is not your PR

**Comment by mbeacom** [comment]
@owocki I haven't forgotten about this! - I'm trying to determine a good route to integrate the steps outlined at:  https://docs.google.com/document/d/1fr4qM84LvrHXL67exMVmPSh46J1kUGrefv88C8enrcs/edit

**Comment by owocki** [comment]
maybe as a PR onto my branch?  or just commenting in places where we need to resolve the dissonance between the two proposals?

**Pull request merged**
